"""capture_frames --engine local: one download per video, a PNG per step t_start, video deleted.

No network: the downloader is replaced by a fetch that hands back a tiny fixture video
generated by ffmpeg into tmp_path, and the frames gate is stubbed so the shared state file
under DATA_DIR is never touched.
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
import capture_frames as cf
import ratelimit

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not installed")

VID = "fixtureVid1"
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"


@pytest.fixture(scope="module")
def fixture_video(tmp_path_factory):
    """A 6-second 320x240 test pattern: the 'tiny local fixture video'."""
    out = tmp_path_factory.mktemp("fixture") / "fixture.mp4"
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i",
                    "testsrc=duration=6:size=320x240:rate=10", "-pix_fmt", "yuv420p", str(out)],
                   check=True, stdin=subprocess.DEVNULL)
    return out


@pytest.fixture
def env(tmp_path, monkeypatch, fixture_video):
    """DATA_DIR -> tmp, gate stubbed, fetch counts calls and copies the fixture into a run dir."""
    monkeypatch.setattr(cf, "DATA_DIR", tmp_path)
    calls = {"gate": 0, "fetch": 0, "outcomes": []}
    monkeypatch.setattr(ratelimit, "check_gate", lambda *a, **k: calls.__setitem__("gate", calls["gate"] + 1))
    monkeypatch.setattr(ratelimit, "record_outcome", lambda ok, *a, **k: calls["outcomes"].append(ok))

    def fetch(video_id, runs_dir):
        calls["fetch"] += 1
        run = Path(runs_dir) / f"run-{calls['fetch']}"
        run.mkdir(parents=True)
        video = run / "video.mp4"
        shutil.copy(fixture_video, video)
        return {"video_path": str(video), "run_dir": str(run), "downloaded": True}

    calls["fn"] = fetch
    return tmp_path, calls


def _session():
    def step(i, t):
        return {"video_id": VID, "index": i, "t_start": t, "t_end": t + 1, "phase": None,
                "action": "a", "app": "CC5", "ui_path": [], "ui_kind": "other", "ui_target": "",
                "ui_options": [], "parameters": {}, "result": "", "frame_ref": None,
                "confidence": "spoken"}
    return {"videos": [{"id": VID}],
            "analysis": {"workflow_steps": [step(1, 1), step(2, 3), step(3, 99)],
                         "key_moments": [{"video_id": VID, "timestamp": 4, "label": "l",
                                          "description": "d"}]}}


def test_one_download_png_per_step_video_deleted(env):
    data_dir, calls = env
    d = _session()
    summary = cf.capture_session_frames_local(d, verbose=False, fetch=calls["fn"])

    assert calls["fetch"] == 1 and calls["gate"] == 1 and calls["outcomes"] == [True]
    steps = d["analysis"]["workflow_steps"]
    assert steps[0]["frame_ref"] == f"frames/{VID}_1.png"
    assert steps[1]["frame_ref"] == f"frames/{VID}_3.png"
    for ref in (steps[0]["frame_ref"], steps[1]["frame_ref"]):
        assert (data_dir / ref).read_bytes()[:8] == PNG_MAGIC      # a real PNG, not a renamed JPEG
    assert (data_dir / "frames" / f"{VID}_4.png").exists()          # key_moment timestamp swept too
    # t=99 is past the 6s fixture: null, with a reason, counted as a failure
    assert steps[2]["frame_ref"] is None
    assert summary["failed"] == 1 and "past the end" in summary["failures"][f"{VID}_99"]
    assert summary["captured"] == 3 and summary["downloads"] == 1
    # the downloaded video is deleted, and no cue scratch dir is left behind
    assert not list((data_dir / "media_runs").glob("run-*"))
    assert not list((data_dir / "frames").glob("cues-*"))
    assert "base64" not in json.dumps(d)


def test_fully_cached_video_never_downloads(env):
    data_dir, calls = env
    frames = data_dir / "frames"
    frames.mkdir()
    for t in (1, 3, 99, 4):
        (frames / f"{VID}_{t}.png").write_bytes(PNG_MAGIC)
    d = _session()
    summary = cf.capture_session_frames_local(d, verbose=False, fetch=calls["fn"])
    assert calls["fetch"] == 0 and calls["gate"] == 0
    assert summary["downloads"] == 0 and summary["failed"] == 0
    assert d["analysis"]["workflow_steps"][2]["frame_ref"] == f"frames/{VID}_99.png"


def test_gate_cooling_stops_without_network(env, monkeypatch):
    _, calls = env

    def cooling(*a, **k):
        raise ratelimit.RateLimited(0, "test cooldown")
    monkeypatch.setattr(ratelimit, "check_gate", cooling)
    d = _session()
    summary = cf.capture_session_frames_local(d, verbose=False, fetch=calls["fn"])
    assert summary["stopped_by_gate"] and calls["fetch"] == 0
    assert all(s["frame_ref"] is None for s in d["analysis"]["workflow_steps"])


def test_download_failure_is_reasoned_and_recorded(env):
    data_dir, calls = env

    def broken(video_id, runs_dir):
        run = Path(runs_dir) / "run-x"     # the lifted downloader leaves this behind on failure
        run.mkdir(parents=True)
        (run / "video.info.json").write_text("{}")
        raise SystemExit("yt-dlp failed (exit 1): WARNING: Your yt-dlp version is old!\n"
                         "ERROR: unable to download video data: HTTP Error 403: Forbidden")
    d = _session()
    summary = cf.capture_session_frames_local(d, verbose=False, fetch=broken)
    assert calls["outcomes"] == [False]
    assert summary["failed"] == 4
    assert all("HTTP Error 403" in r for r in summary["failures"].values())   # the ERROR line, not the WARNING
    assert not list((data_dir / "media_runs").iterdir())                     # no leaked run dir


def test_session_file_engine_local_and_stream_untouched(env, monkeypatch):
    data_dir, calls = env
    sdir = data_dir / "sessions" / "s1"
    sdir.mkdir(parents=True)
    (sdir / "comparison_data.json").write_text(json.dumps(_session()), encoding="utf-8")
    monkeypatch.setattr(cf, "_download_video", calls["fn"])
    summary = cf.capture_session_file(str(sdir), verbose=False, engine="local")
    assert summary["engine"] == "local"
    written = json.loads((sdir / "comparison_data.json").read_text(encoding="utf-8"))
    assert written["analysis"]["workflow_steps"][0]["frame_ref"] == f"frames/{VID}_1.png"
    # stream stays the default engine and is still the original function
    seen = {}
    monkeypatch.setattr(cf, "capture_session_frames",
                        lambda data, out, verbose=True: seen.setdefault("stream", True) and {"captured": 0})
    cf.capture_session_file(str(sdir), verbose=False)
    assert seen == {"stream": True}
    with pytest.raises(ValueError):
        cf.capture_session_file(str(sdir), engine="bogus")


def test_mcp_harvest_frames_engine_local(env, monkeypatch):
    data_dir, calls = env
    mcp_server = pytest.importorskip("mcp_server")
    sdir = data_dir / "sessions" / "s1"
    sdir.mkdir(parents=True)
    (sdir / "comparison_data.json").write_text(json.dumps(_session()), encoding="utf-8")
    monkeypatch.setattr(cf, "_download_video", calls["fn"])
    monkeypatch.setattr(mcp_server, "DATA_DIR", data_dir)
    monkeypatch.setattr(ratelimit, "status", lambda *a, **k: {"blocked": False, "seconds_left": 0})
    out = json.loads(mcp_server.harvest_frames(str(sdir), engine="local"))
    assert out["engine"] == "local" and out["captured"] >= 2 and calls["fetch"] == 1
    bad = json.loads(mcp_server.harvest_frames(str(sdir), engine="bogus"))
    assert bad["status"] == "failed"
